language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dnayak47/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dnayak47/docker-react npm run test